const constants = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  SET_GOAL: "SET_GOAL",
  CLEAR_ERROR: "CLEAR_ERROR",
  FETCH_BRAND_NAMES: "FETCH_BRAND_NAMES",
  CANCEL_FETCHING: "CANCEL_FETCHING",
  CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
  CLEAR_SUGGETIONS: "CLEAR_SUGGETIONS"
}

export default constants;
