const constants = {
  NEXT_STEP: "NEXT_STEP",
  START_CHAT: "START_CHAT",
  SEND_PW_REQUEST: "SEND_PW_REQUEST",
  GET_PASSWORD: "GET_PASSWORD",
  REDIRECT_PORTFOLIO: "REDIRECT_PORTFOLIO",
  DOWNLOAD_CV: "DOWNLOAD_CV",
  SHOW_CARDS: "SHOW_CARDS",
  SHOW_OPTIONS: "SHOW_OPTIONS"
}
// const constants = {
//   ADD_ITEM: "ADD_ITEM",
//   REMOVE_ITEM: "REMOVE_ITEM",
//   SET_GOAL: "SET_GOAL",
//   CLEAR_ERROR: "CLEAR_ERROR",
//   FETCH_BRAND_NAMES: "FETCH_BRAND_NAMES",
//   CANCEL_FETCHING: "CANCEL_FETCHING",
//   CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
//   CLEAR_SUGGETIONS: "CLEAR_SUGGETIONS"
// }

export default constants;
